server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:9998}/wordcounter-history-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update